version: '3.7'
services:
  nexus3:
    image: sonatype/nexus3
    container_name: basic-nexus
    restart: always
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/var/nexus-data

volumes:
  nexus-data:
    driver: local


