version: '3.5'
services:
  redis:
    image: redis:6.2.7
    container_name: my_redis
    command: redis-server /usr/local/etc/redis/redis.conf
#    command: redis-server /usr/local/etc/redis/redis.conf --requirepass Sjs.379=  #可以覆盖设置密码
    restart: always
    networks:
      - sjs-net
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      # 替换容器内redis.conf
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf


#自定义网络
networks:
  sjs-net:
    external: true

