version: '3.5'
services:
  timescaledb:
    image: emqx/emqx:latest
    container_name: basic-emqx
    restart: unless-stopped             # 设置重启策略不断的重启
    ports:
      - 1883:1883
      - 18083:18083