version: '3.5'
services:
  emqx-service:
    image: emqx/emqx:4.2.14
    container_name: basic-emqx
    user: root
    restart: unless-stopped             # 设置重启策略不断的重启
    environment:
      - "EMQX_NAME=emqx"
      - "EMQX_HOST=127.0.0.1"
      - "EMQX_ACL_NOMATCH=deny"
      - "EMQX_ALLOW_ANONYMOUS=false"
      - "EMQX_LOADED_PLUGINS=emqx_auth_username"
      - "EMQX_AUTH__USER__1__USERNAME=mqprd"
      - "EMQX_AUTH__USER__1__PASSWORD=fbjLcBESCppsd2dn"
      - "EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=x8n7w3v8p2"
    networks:
      - sjs-net
#    volumes:
#      - vol-emqx:/opt/emqx/data/mnesia
    ports:
      - "1883:1883"
      - "18083:18083"
      - "9083:8083"
      - "9084:8084"
      - "9081:8081"

#1883        MQTT TCP 协议端口
#9083        WebSocket 端口
#9084        WebSocket with SSL 端口
#18083       管理控制台端口
#9081        http:management
#8883        mqtt:ssl

#volumes:
#  vol-emqx:
#    name: tsl-emqx

#自定义网络
networks:
  sjs-net:
    external: true

