version: "3"
services:

  java:
    image: registry.cn-hangzhou.aliyuncs.com/iothub-test/ms-aa:s7-3
    ports:
      - "20040:20040"
    networks:
      - iot-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    extra_hosts:
      - "nacos1:192.168.231.26"
      - "nacos2:192.168.231.26"
                
networks:
  iot-net:
    external: true
