version: "3"
services:

  java:
    image: registry.cn-hangzhou.aliyuncs.com/iothub-test/gateway:s7-4
    ports:
      - "20020:20020"
    networks:
      - iot-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname==docker1
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    extra_hosts:
      - "nacos1:192.168.231.26"
      - "nacos2:192.168.231.26"

networks:
  iot-net:
    external: true
