version: "3"
services:
  java:
    image: registry.cn-hangzhou.aliyuncs.com/iothub-test/ms-alarm:s6-74
    depends_on:
      - config-server
      - ms-auth
      - gateway
    ports:
      - "20160:20160"
    networks:
      - iot-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.hostname!=docker6
    environment:
      - "SPRING_PROFILES_ACTIVE=prod-yangzijiang"
      - "SPRING_CLOUD_CONFIG_PROFILE=prod-yangzijiang"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.231.21:20000/eureka/"
      - "SPRING_CLOUD_CONFIG_URI=http://192.168.231.26:20010"
    extra_hosts:
      - "eureka1:192.168.231.21"
networks:
  iot-net:
    external: true
