version: "3"
services:

  ms-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/iothub-test/gateway:s6-122
    ports:
      - "20020:20020"
    networks:
      - iot-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname==docker1
    environment:
      - "SPRING_PROFILES_ACTIVE=prod-yangzijiang"
      - "SPRING_CLOUD_CONFIG_PROFILE=prod-yangzijiang"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.231.21:20000/eureka/"
      - "SPRING_CLOUD_CONFIG_URI=http://192.168.231.26:20010"
    extra_hosts:
      - "eureka1:192.168.231.21"
      - "eureka2:192.168.231.21"

networks:
  iot-net:
    external: true
