version: "3"
services:

  java:
    image: registry.cn-hangzhou.aliyuncs.com/iothub-test/ms-rest-b:s7-49
    ports:
      - "20220:20220"
    networks:
      - iot-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==worker
          - node.hostname!=docker6
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    extra_hosts:
      - "nacos1:192.168.231.26"
      - "nacos2:192.168.231.26"

networks:
  iot-net:
    external: true
