version: "3"
services:
     
  java:
    image: registry.cn-hangzhou.aliyuncs.com/iothub-test/st-calibration:s7-9
    ports:
      - "20158:20158"
    networks:
      - iot-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==docker2
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    extra_hosts:
      - "nacos1:192.168.231.26"
      - "nacos2:192.168.231.26"
                                                      
networks:
  iot-net:
    external: true
