global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.sina.com:465'             #邮箱smtp服务器代理，启用SSL发信, 端口一般是465
  smtp_from: 'zhangdongsheng2@sina.com'              #发送邮箱名称
  smtp_auth_username: 'zhangdongsheng2@sina.com'              #邮箱名称
  smtp_auth_password: 'b77557d08a0dda10'                #邮箱密码或授权码
  smtp_require_tls: false

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname']

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'default'
    email_configs:
      - to: '569143958@qq.com'
        send_resolved: true
    webhook_configs:
      - url: 'http://dingtalk:8060/dingtalk/webhook/send'
        send_resolved: true
