version: '3'
services:

  #rabbitmq container
  rabbitmq:
    container_name: rabbitmq3.7.27
    #use docker images
    image: rabbitmq:3.7.27-management
    #ports setting
    hostname: myRabbit
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    #volumes setting
    volumes:
      #- ./etc:/etc/rabbitmq/
      - ./data:/var/lib/rabbitmq/
      # - ./logs:/var/log/rabbitmq/log/  #加上日志卷启动会报权限问题
    #环境变量
    environment:
      - RABBITMQ_DEFAULT_VHOST=my_vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin