version: "2"
services:
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
      - SEATA_IP=192.168.130.77
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry.conf
    volumes:
      - ./conf/:/root/seata-config