version: '3.1'
services:
  HAProxy:
    image: 172.16.56.253:3002/haproxy:2.2.3
    restart: always
    container_name:  basic-HAProxy
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy:ro
    network_mode: host