version: '3.1'
services:
  HAProxy:
    image: haproxy:2.2.3
    restart: unless-stopped
    container_name:  basic-HAProxy
#    ports:
#      - 4100:80
#      - 4000:4000
#      - 1080:1080
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    network_mode: host