ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}

#ENV http_proxy "http://tw.twgiot.com:37890"
#ENV https_proxy "http://tw.twgiot.com:37890"
#ENV ftp_proxy "http://tw.twgiot.com:37890"

# Add your logstash plugins setup here
#RUN logstash-plugin install logstash-filter-json

# 安装一个json插件.
#RUN bin/logstash-plugin install logstash-codec-json_lines



