version: '3'
services:
  mysql:
    hostname: mysql8
    image: mysql:8.0.28
    container_name: mysql8 # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: unless-stopped # 设置容器自启模式
    networks:
      - sjs-net
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=Sjs.379= # 设置root密码
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
    ports:
      - "33006:3306"


#自定义网络
networks:
  sjs-net:
    external: true
