version: '3.3'
# docker-compose restart base-api 重启服务端
# docker network create --driver=bridge --subnet=172.3.0.0/16 sjs-net
services:
  #前端
  pad-web:
    image: node:latest
    container_name: pad-web
    restart: always # 容器总是重新启动
    working_dir: /usr/src/app/
    command: /bin/bash -c "yarn install && npm run start"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - sjs-net
    ports:
      - "3333:3333"
    volumes:
      - ./pad-web/:/usr/src/app/  #打包好的文件放 web 文件夹中，然后刷新浏览器
    extra_hosts:
      - "dpjh-api-server:10.37.127.22"




#自定义网络
networks:
  sjs-net:
    external: true








