# 构建镜像，执行命令：【docker build -t twdt_web:2.0 .】
FROM nginx:stable-alpine

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./docker-entrypoint.sh /docker-entrypoint.d/my.sh
RUN chmod +x /docker-entrypoint.d/my.sh


WORKDIR /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
ADD default.conf /etc/nginx/conf.d/