version: '3.5'
services:

  redis:
    image: redis:latest
    container_name: wxwl_redis
    restart: unless-stopped # 设置容器自启模式
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      # 替换容器内redis.conf
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf

  mysql:
    hostname: mysql
    image: mysql:5.7.22
    container_name: mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: unless-stopped # 设置容器自启模式
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"


  kodbox:
    hostname: kodbox
    image: registry.cn-shanghai.aliyuncs.com/wxwl/kodbox:1.0
    container_name: kodbox # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: unless-stopped # 设置容器自启模式
    volumes:
      - "./data:/code/medata"
    ports:
      - "20001:80"
    command: chmod 777 . && /init.sh



